import 'models/count_item.dart';

List<CountItem> countItemsMock = [
  CountItem(name: 'ибискус розовый', value: 4, id: 1),
  CountItem(name: 'ибискус Белые', value: 1, id: 1),
  CountItem(name: 'фундук', value: 21, id: 1),
  CountItem(name: 'вишня', value: 3, id: 1),
  CountItem(name: 'черешня', value: 2, id: 1),
  CountItem(name: 'бузина декоративная', value: 5, id: 1),
  CountItem(name: 'айва', value: 2, id: 1),
  CountItem(name: 'ЯБЛОНЯ дикая', value: 32, id: 1),
  CountItem(name: 'ЯБЛОНЯ', value: 24, id: 1),
  CountItem(name: 'кизил культурный', value: 2, id: 1),
  CountItem(name: 'кипарис', value: 5, id: 1),
  CountItem(name: 'ТУЯ', value: 40, id: 1),
  CountItem(name: 'алыча дикая', value: 10, id: 1),
  CountItem(name: 'бобовник', value: 1, id: 1),
  CountItem(name: 'слива', value: 3, id: 1),
  CountItem(name: 'куст будлея давида', value: 1, id: 1),
  CountItem(name: 'сирень', value: 1, id: 1),
  CountItem(name: 'сперея японская', value: 2, id: 1),
  CountItem(name: 'можжевельник казацкий', value: 6, id: 1),
  CountItem(name: 'розмарин', value: 2, id: 1),
  CountItem(name: 'лаванда', value: 1, id: 1),
  CountItem(name: 'сперея серая', value: 4, id: 1),
  CountItem(name: 'Махония', value: 2, id: 1),
  CountItem(name: 'сантолина', value: 2, id: 1),
  CountItem(name: 'кизильник', value: 2, id: 1),
  CountItem(name: 'можжевельник ползучий', value: 7, id: 1),
  CountItem(name: 'барбарис красный', value: 2, id: 1),
  CountItem(name: 'шалфей лекарственный', value: 5, id: 1),
  CountItem(name: 'самшит', value: 6, id: 1),
  CountItem(name: 'гвоздика', value: 1, id: 1),
  CountItem(name: 'айва японская', value: 2, id: 1),
  CountItem(name: 'сперея японская', value: 2, id: 1),
  CountItem(name: 'чайная Роза', value: 1, id: 1),
  CountItem(name: 'Юка', value: 3, id: 1),
  CountItem(name: 'малиновое дерево', value: 1, id: 1),
  CountItem(name: 'туя Голден', value: 4, id: 1),
  CountItem(name: 'желтые цветочки по весне', value: 4, id: 1),
  CountItem(name: 'можжевельник', value: 11, id: 1),
  CountItem(name: 'чубушник', value: 3, id: 1),
  CountItem(name: 'липа', value: 7, id: 1),
  CountItem(name: 'чабрец садовый', value: 6, id: 1),
  CountItem(name: 'чабрец дикий', value: 3, id: 1),
  CountItem(name: 'ГРУША', value: 19, id: 1),
  CountItem(name: 'яблоня декоративная', value: 20, id: 1),
  CountItem(name: 'пузыреплодник', value: 2, id: 1),
  CountItem(name: 'сосна Крымская', value: 1, id: 1),
  CountItem(name: 'рябина желтая', value: 11, id: 1),
  CountItem(name: 'жимолость японская', value: 6, id: 1),
  CountItem(name: 'ШИПОВНИК', value: 8, id: 1),
  CountItem(name: 'смородина альпийская', value: 2, id: 1),
  CountItem(name: 'фисташка плодовая', value: 8, id: 1),
  CountItem(name: 'Роза декоративная', value: 13, id: 1),
  CountItem(name: 'ГРУША дикая ', value: 12, id: 1),
  CountItem(name: 'гранаты', value: 6, id: 1),
  CountItem(name: 'хурма', value: 2, id: 1),
  CountItem(name: 'азимина', value: 2, id: 1),
  CountItem(name: 'кедры атласский', value: 4, id: 1),
  CountItem(name: 'боярышник плодовый', value: 2, id: 1),
  CountItem(name: 'агапантус', value: 1, id: 1),
  CountItem(name: 'клён', value: 18, id: 1),
  CountItem(name: 'клён американский', value: 6, id: 1),
  CountItem(name: 'орех грецкий', value: 7, id: 1),
  CountItem(name: 'дуб', value: 2, id: 1),
  CountItem(name: 'слива декоративная', value: 38, id: 1),
  CountItem(name: 'миндаль горький', value: 3, id: 1),
  CountItem(name: 'тёрен', value: 1, id: 1),
  CountItem(name: 'граб', value: 4, id: 1),
  CountItem(name: 'платан', value: 3, id: 1),
  CountItem(name: 'дуб колонновидный', value: 1, id: 1),
  CountItem(name: 'клён шаровидный', value: 2, id: 1),
  CountItem(name: 'ТУЯ колоновидная', value: 1, id: 1),
  CountItem(name: 'глициния', value: 1, id: 1),
  CountItem(name: 'барбарис', value: 2, id: 1),
  CountItem(name: 'такома', value: 1, id: 1),
  CountItem(name: 'персик плодовый', value: 6, id: 1),
  CountItem(name: 'персик декоративный', value: 10, id: 1),
  CountItem(name: 'тамарикс', value: 3, id: 1),
];
